version: "3"
services:
  web:
    image: nginx:alpine
    volumes:
      - murdock-html:/murdock/html:ro
      - murdock-data:/murdock/data:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 8081:80
    restart: always
    depends_on:
      - murdock
  murdock:
    image: murdock:latest
    build: ./murdock
    volumes:
      - murdock-conf:/murdock
      - murdock-data:/murdock/data
    restart: always
  disque:
    image: richnorth/disque
    expose:
      - "7711"
    restart: always
  ssh:
    image:  panubo/sshd
    restart: always
    environment:
      - SSH_USERS=murdock-slave:1000:1000
      - TCP_FORWARDING=true
      - DISABLE_SCP=true
    volumes:
      - murdock-ssh-host-keys:/etc/ssh/keys
      - murdock-ssh-slave-keys:/etc/authorized_keys
    ports:
      - "2222:22"

volumes:
  murdock-html:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/murdock/html
  murdock-conf:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/murdock
  murdock-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/murdock/data
  murdock-ssh-host-keys:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/murdock/ssh-host-keys
  murdock-ssh-slave-keys:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /srv/murdock/ssh-slave-keys
